### ISSUE TITLE
カウント止める用の変数の型は int ではなく boolean にすべきでは？

### ISSUE THREAD

**Issue by syasin-5d** [taiseiyo/heroku#2]
該当箇所: https://github.com/taiseiyo/heroku/blob/ef118a1250bf0082b6805d8cc443458c86559053/myproj/diary/static/bingo.js#L3

参考: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Boolean

**Comment by taiseiyo** [comment]
確かに笑

見るの早いなーー
さすがやな笑笑

**Comment by taiseiyo** [comment]
修正できたーー（＾＾）
